[package]
name = "fmp"
version = "0.1.0"
authors = ["Brian Carrigan <brian@bcarrigan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
regex = "1"
